[phases.setup]
nixPkgs = ["php81", "php81Packages.composer"]

[phases.build]
cmd = "composer install --no-dev --optimize-autoloader || true"

[phases.start]
cmd = "php -S 0.0.0.0:$PORT index.php"

[variables]
PORT = "8000" 